# -*- coding: utf-8 -*-
"""Customer_Churn_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G09sKY1LDIm0ujN3l3BaHTQ4Hij-A8e8

# Penerapan Data Mining untuk Prediksi Customer Churn dalam Mendukung Strategi Retensi Pelanggan

#### **Nama:** Nurnmalia Indriyani Putri

#### **NIM:** 2310512155

#### **Kelas:** B  

#### **Mata Kuliah:** Data Mining & Data Warehouse
---

## 1. BUSINESS UNDERSTANDING

### 1.1 Latar Belakang
Customer churn menjadi tantangan kritis bagi perusahaan berbasis subscription karena mempertahankan pelanggan lama jauh lebih efisien secara biaya dibanding mencari pelanggan baru, dengan selisih hingga 5–7 kali lipat.

Oleh karena itu, kemampuan memprediksi pelanggan yang berpotensi churn, sehingga perusahaan bisa melakukan intervensi lebih awal seperti pemberian promo, peningkatan layanan, atau pendekatan personal untuk mempertahankan pelanggan tersebut.

### 1.2 Tujuan Bisnis
Membangun model prediksi untuk mengidentifikasi pelanggan yang berpotensi churn, sehingga perusahaan dapat melakukan intervensi lebih awal (promo, diskon, layanan khusus).

### 1.3 Business Questions
1. Berapa tingkat churn saat ini?
2. Profil pelanggan seperti apa yang paling sering churn?
3. Faktor apa yang paling berkorelasi dengan churn?
4. Apakah jenis kontrak dan paket berpengaruh terhadap churn?

### 1.4 Tujuan Data Mining
Membangun model klasifikasi yang dapat memprediksi status churn seorang pelanggan berdasarkan karakteristik dan pola penggunaannya, sehingga hasil prediksi tersebut bisa dijadikan dasar bagi tim bisnis untuk menentukan pelanggan mana yang perlu diintervensi lebih dulu.

### 1.5 Jenis Learning: Supervised Learning
Dataset memiliki label target yaitu kolom Churn (0 atau 1)

### 1.6 Formulasi Data Mining : **Klasifikasi**
Alasan :
1. Target variabel adalah biner (0 atau 1)
Churn hanya punya dua nilai, yaitu pelanggan churn atau tidak churn
- `Churn = 1` → Pelanggan berhenti (label positif)
- `Churn = 0` → Pelanggan masih aktif (label negatif)
2.  Interpretabilitas tinggi, setiap fitur punya koefisien yang bisa dijelaskan langsung ke stakeholder
3. Cocok sebagai baseline
4. Efisien untuk dataset besar

### 1.7 Kriteria Sukses
1.  Recall (≥75%) dipilih sebagai metrik utama karena fokus project adalah mendeteksi sebanyak mungkin pelanggan yang akan churn agar bisa diintervensi lebih awal, sementara Accuracy, Precision, dan F1-Score tidak dipakai karena masing-masing kurang fokus pada hal itu (Accuracy hanya melihat ketepatan keseluruhan, Precision malah menekan False Positive yang risikonya lebih ringan, dan F1-Score menyeimbangkan precision-recall padahal project ini sengaja berat ke recall saja)
2.  AUC-ROC (≥0,85) dipilih sebagai metrik pendamping untuk memastikan model punya kemampuan membedakan churn vs tidak churn yang kuat di berbagai threshold, bukan cuma bagus di satu titik potong saja

---
## 2. DATA UNDERSTANDING

Step :
1. Import Library
2. Load Data
3. Struktur, tipe data, deskripsi, rentang nilai, dan statistik deskriptif
4. Pengecekan Missing Value
5. Distribusi Target
6. Korelasi

### 2.1 Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from matplotlib.gridspec import GridSpec
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    confusion_matrix, classification_report,
    recall_score, f1_score, roc_auc_score, roc_curve
)

plt.rcParams['figure.figsize'] = (10, 6)
plt.rcParams['font.size'] = 12
sns.set_style('whitegrid')
sns.set_palette('Set2')


print('Library berhasil diimport!')

"""### 2.2 Load Dataset"""

import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Customer Churn_Data Mining/customer_churn_dataset-training-master.csv'

df = pd.read_csv(file_path)

print('Dataset berhasil dimuat!')
print(f'Shape: {df.shape[0]:,} baris × {df.shape[1]} kolom')

"""Insight : Dataset berisi 440.833 data dan terdiri dari 12 kolom

### 2.3 Gambaran Umum Dataset
"""

# Tampilkan 10 baris pertama
df.head(10)

# Informasi tipe data
df.info()

"""Temuan :
1.   Perlu mengubah tipe data pada kolom
*   Gender (object) → Karena berisi nilai kategorikal (Male & Female), algoritma tidak bisa memproses data yang bersifat teks
*   Subscription type (object) → Berisi nilai teks, harus diubah ke numerik (0/1/2) agar bisa diproses algoritma
*   Contract Length (object) → Berisi nilai teks (Monthly/Quarterly/Annual), harus diubah ke numerik (0/1/2) agar bisa diproses algoritma
*   Churn (float64) → Merupakan label kategori biner (0 atau 1), bukan nilai desimal, sehingga diubah ke int agar tipe datanya sesuai dengan makna sebenarnya sebagai label klasifikasi

2.   Terdapat fitur yang tidak relevan (CustomerID) → CustomerID hanyalah nomor urut identitas unik setiap pelanggan yang tidak memiliki makna bisnis, jika tidak di drop akan beresiko terjadi overfitting, prediksi menjadi tidak akurat, dan terjadi rawan terjadi noise


"""

# Statistik deskriptif
df.describe().round(2)

"""Insight :

1.   Tidak ada outlier ekstrem
*   Nilai minimum dan maksimum pada setiap fitur masih berada dalam rentang yang wajar dan sesuai konteks bisnis pelanggan
*   Tidak terlihat adanya nilai yang sangat jauh dari distribusi mayoritas data yang berpotensi mengganggu proses pemodelan

2.   Distribusi data cukup normal/seimbang
*   Nilai mean dan median pada sebagian besar fitur cukup berdekatan, seperti Age (39,37 vs 39) dan Usage Frequency (15,81 vs 16)
*   Hal ini menunjukkan distribusi data tidak terlalu miring (skewed) dan representatif terhadap populasi pelanggan

3.   Target Churn cukup proporsional
*   Rata-rata nilai Churn = 0,57, yang berarti sekitar 57% pelanggan churn dan 43% tidak churn
*   Komposisi kelas yang relatif seimbang ini membantu model belajar dengan lebih baik tanpa masalah ketidakseimbangan kelas yang signifikan


4.   Skala antar fitur sangat berbeda
*   Beberapa fitur memiliki rentang nilai yang kecil, seperti Support Calls (0–10), sedangkan fitur lain memiliki rentang yang jauh lebih besar, seperti Total Spend (100–1000) dan CustomerID (2–449999)
*   Perbedaan skala ini menunjukkan perlunya proses feature scaling/normalisasi untuk algoritma yang sensitif terhadap skala data


5.   Fitur perilaku punya variasi tinggi
*   Fitur seperti Tenure (std = 17,26), Usage Frequency (std = 8,59), Payment Delay (std = 8,26), dan Last Interaction (std = 8,60) memiliki penyebaran data yang cukup besar
*   Variasi ini mengindikasikan adanya perbedaan perilaku yang signifikan antar pelanggan, sehingga fitur-fitur tersebut berpotensi menjadi prediktor penting dalam mendeteksi churn

### 2.4 Data Dictionary

| Kolom | Tipe | Deskripsi |
|---|---|---|
| `CustomerID` | int | ID unik pelanggan |
| `Age` | int | Usia pelanggan (18–65 tahun) |
| `Gender` | str | Jenis kelamin (Male / Female) |
| `Tenure` | int | Lama berlangganan (bulan) |
| `Usage Frequency` | int | Frekuensi penggunaan layanan |
| `Support Calls` | int | Jumlah panggilan ke customer support |
| `Payment Delay` | int | Keterlambatan pembayaran (hari) |
| `Subscription Type` | str | Jenis paket (Basic / Standard / Premium) |
| `Contract Length` | str | Panjang kontrak (Monthly / Quarterly / Annual) |
| `Total Spend` | int | Total pengeluaran pelanggan |
| `Last Interaction` | int | Hari sejak interaksi terakhir |
| `Churn` | int | Target: 1 = churn, 0 = tidak churn |

### 2.5 Analisis Missing Values
"""

# Hitung missing values
missing = df.isnull().sum().reset_index()
missing.columns = ['Kolom', 'Jumlah Missing']
missing['Persentase (%)'] = (missing['Jumlah Missing'] / len(df) * 100).round(4)
missing = missing[missing['Jumlah Missing'] > 0].sort_values('Jumlah Missing', ascending=False)

print('=== Missing Values ===')
print(missing.to_string(index=False))
print(f'\nTotal baris dengan setidaknya 1 missing: {df.isnull().any(axis=1).sum():,}')

"""Temuan :
 Terdapat 1 missing values atau sekitar 0.0002% pada setiap kolom, hal itu dikarenakan pada dataset asli di baris terakhir terdapat baris kosong

"""

# Visualisasi missing values
fig, ax = plt.subplots(figsize=(10, 4))
cols_with_missing = df.columns[df.isnull().any()]
missing_pct = (df[cols_with_missing].isnull().sum() / len(df) * 100)

bars = ax.barh(missing_pct.index, missing_pct.values, color='#e74c3c', alpha=0.8)
ax.set_xlabel('Persentase Missing (%)')
ax.set_title('Missing Values per Kolom', fontweight='bold')
for bar, val in zip(bars, missing_pct.values):
    ax.text(bar.get_width() + 0.0001, bar.get_y() + bar.get_height()/2,
            f'{val:.4f}%', va='center', fontsize=10)
plt.tight_layout()
plt.show()

"""### 2.6 Analisis Distribusi Target (Churn)"""

churn_counts = df['Churn'].value_counts()
churn_pct = df['Churn'].value_counts(normalize=True) * 100

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Bar chart
colors = ['#2ecc71', '#e74c3c']
bars = axes[0].bar(['Tidak Churn (0)', 'Churn (1)'], churn_counts.values, color=colors, alpha=0.85, edgecolor='white', linewidth=1.5)
axes[0].set_title('Distribusi Churn', fontweight='bold')
axes[0].set_ylabel('Jumlah Pelanggan')
for bar in bars:
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2000,
                 f'{bar.get_height():,.0f}', ha='center', fontweight='bold')

# Pie chart
axes[1].pie(churn_counts.values, labels=['Tidak Churn', 'Churn'],
            colors=colors, autopct='%1.1f%%', startangle=90,
            wedgeprops={'edgecolor': 'white', 'linewidth': 2})
axes[1].set_title('Proporsi Churn', fontweight='bold')

plt.suptitle(f'Total: {len(df):,} pelanggan', fontsize=11, y=0.02)
plt.tight_layout()
plt.show()

print(f'Churn    : {churn_counts[1]:,} pelanggan ({churn_pct[1]:.1f}%)')
print(f'Tidak    : {churn_counts[0]:,} pelanggan ({churn_pct[0]:.1f}%)')

"""Insight :

*   Berdasarkan visualisasi pada bar chart dan pie chart yang didapatkan pada kolom churn pada dataset asli, terlihat bahwa perbadingan pelanggan yang berpotensi churn dan tidak churn terhadap total pelanggan hampir diakatakan seimbang dengan **43, 3%** adalah pelanggan yang berpotensi tidak churn dan **56, 7%** pelanggan yang berpotensi churn
*   Oleh karena itu tidak perlu menggunakan teknik **SMOTE (Synthetic Minority Over-sampling Technique)**, karena berdasarkan hasil perbandingan distribusi diatas sudah relatif hampir seimbang antara pelanggan yang berpotensi churn dan tidak churn. Alternatifnya menggunakan class_weight='balanced' untuk memberikan bobot yang lebih besar pada kelas yang jumlahnya lebih sedikit sehingga model tidak bias terhadap kelas mayoritas. Metode ini akan jauh lebih efektif karena tidak manambah data sintetis dan tetap membantu meningkatkan kemampuan model untuk mendeteksi pelanggan yang berpotensi churn


"""

# Profil rata-rata pelanggan churn vs tidak churn
numeric_cols = ['Age', 'Tenure', 'Usage Frequency', 'Support Calls',
                'Payment Delay', 'Total Spend', 'Last Interaction']

profil = df.groupby('Churn')[numeric_cols].mean().T
profil.columns = ['Tidak Churn', 'Churn']
profil['Selisih'] = profil['Churn'] - profil['Tidak Churn']
profil['Arah'] = profil['Selisih'].apply(lambda x: '⬆️ Lebih Tinggi' if x > 0 else '⬇️ Lebih Rendah')

print('Profil Rata-rata Pelanggan:')
print('='*65)
print(profil.round(2).to_string())
print('='*65)

"""Insight :


1.   Pelanggan churn cenderung lebih tua
*   Rata-rata usia pelanggan churn 41,75 tahun, lebih tinggi dibanding pelanggan yang tetap bertahan (36,26 tahun)
*   Hal ini menunjukkan pelanggan pada kelompok usia tertentu mungkin memiliki kebutuhan atau ekspektasi yang belum terpenuhi

2.   Pelanggan churn memiliki masa berlangganan lebih pendek
*   Rata-rata Tenure pelanggan churn lebih rendah (30,47 bulan) dibanding pelanggan yang tidak churn (32,28 bulan)
*   Artinya, pelanggan yang belum terlalu lama menggunakan layanan cenderung lebih mudah meninggalkan perusahaan

3. Frekuensi penggunaan layanan lebih rendah
*   Pelanggan churn menggunakan layanan sedikit lebih jarang (15,46) dibanding pelanggan yang bertahan (16,26)
*   Semakin rendah tingkat penggunaan, semakin rendah keterikatan pelanggan terhadap layanan

4. Jumlah keluhan (Support Calls) jauh lebih tinggi
*   Pelanggan churn rata-rata melakukan 5,14 panggilan dukungan, sedangkan pelanggan yang bertahan hanya 1,59
*   Ini menunjukkan masalah atau keluhan yang tidak terselesaikan dengan baik dapat meningkatkan risiko churn

5. Keterlambatan pembayaran lebih sering terjadi
*   Pelanggan churn memiliki Payment Delay lebih tinggi (15,22 hari) dibanding pelanggan yang tidak churn (10,02 hari)
*   Keterlambatan pembayaran dapat menjadi indikasi ketidakpuasan atau menurunnya komitmen pelanggan

6. Total pengeluaran lebih rendah
*   Pelanggan churn memiliki rata-rata Total Spend sebesar 541,29, jauh lebih rendah dibanding pelanggan yang bertahan (749,95)
*   Pelanggan dengan nilai transaksi yang rendah cenderung memiliki loyalitas yang lebih rendah

7. Interaksi terakhir lebih lama
*   Nilai Last Interaction pelanggan churn lebih tinggi (15,60) dibanding pelanggan yang tidak churn (13,01)
*   Semakin lama pelanggan tidak berinteraksi dengan layanan, semakin besar kemungkinan mereka berhenti menggunakan layanan

### 2.7 Eksplorasi Fitur Numerik
"""

num_cols = ['Age', 'Tenure', 'Usage Frequency', 'Support Calls',
            'Payment Delay', 'Total Spend', 'Last Interaction']

fig, axes = plt.subplots(3, 3, figsize=(16, 12))
axes = axes.flatten()

for i, col in enumerate(num_cols):
    df_clean = df.dropna(subset=[col, 'Churn'])
    for churn_val, label, color in [(0, 'Tidak Churn', '#2ecc71'), (1, 'Churn', '#e74c3c')]:
        data = df_clean[df_clean['Churn'] == churn_val][col]
        axes[i].hist(data, bins=30, alpha=0.5, label=label, color=color)
    axes[i].set_title(f'Distribusi {col}', fontweight='bold')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Frekuensi')
    axes[i].legend(fontsize=9)

# Sembunyikan subplot kosong
for j in range(len(num_cols), len(axes)):
    axes[j].set_visible(False)

plt.suptitle('Distribusi Fitur Numerik berdasarkan Churn', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.show()

"""Insight :

**1. Distribusi Age (Usia)**
*  Pelanggan Tidak Churn paling banyak berada pada usia sekitar 49–50 tahun dengan frekuensi mencapai ±16.000 pelanggan
*   Pelanggan Churn tersebar cukup merata pada rentang usia 18–65 tahun dengan frekuensi sekitar 10.000–11.000 pelanggan per kelompok usia
*   Interpretasi: Pelanggan yang tidak churn cenderung terkonsentrasi pada usia yang lebih matang (sekitar 50 tahun), sedangkan churn terjadi hampir di semua kelompok usia

**2. Tenure (Lama Berlangganan)**
*    Pada tenure 1–5 bulan, pelanggan Tidak Churn sekitar 4.500–5.000 pelanggan
*    Pada tenure 30–60 bulan, pelanggan Tidak Churn meningkat menjadi sekitar 7.000 pelanggan
*    Pelanggan Churn relatif stabil di kisaran 8.200–8.700 pelanggan pada hampir seluruh rentang tenure
*    Interpretasi: Semakin lama pelanggan berlangganan, jumlah pelanggan yang bertahan (tidak churn) semakin tinggi

**3. Usage Frequency (Frekuensi Penggunaan)**
*    Pada frekuensi penggunaan 1–10 kali, pelanggan Tidak Churn sekitar 5.200–5.400 pelanggan
*    Pada frekuensi 10–30 kali, jumlah Tidak Churn meningkat menjadi sekitar 6.800–7.000 pelanggan
*    Pelanggan Churn berada di kisaran 8.200–8.500 pelanggan pada hampir semua kategori
*    Interpretasi: Pelanggan yang lebih sering menggunakan layanan memiliki kecenderungan lebih besar untuk tetap menjadi pelanggan

**4. Support Calls (Panggilan Dukungan)**
*   Pada 0–2 panggilan, pelanggan Tidak Churn sangat tinggi, yaitu sekitar 45.000–49.000 pelanggan
*   Pada 3 panggilan, turun menjadi sekitar 31.000 pelanggan
*   Pada 4 panggilan, turun lagi menjadi sekitar 16.000 pelanggan
*   Setelah 5 panggilan atau lebih, jumlah Tidak Churn hampir mendekati 0
*   Sebaliknya, pelanggan Churn meningkat dari sekitar 21.000 pelanggan menjadi 24.000 pelanggan pada kategori 5–10 panggilan
*   Interpretasi: Banyaknya panggilan ke customer support merupakan indikator kuat churn. Semakin banyak keluhan atau masalah yang dilaporkan, semakin tinggi kemungkinan pelanggan churn

**5. Payment Delay (Keterlambatan Pembayaran)**
*   Pelanggan Tidak Churn memiliki frekuensi sekitar 9.000 pelanggan pada rentang keterlambatan 0–20 hari
*   Setelah melewati 20 hari, jumlah Tidak Churn hampir tidak ada
*   Pelanggan Churn berada di kisaran 8.000–8.500 pelanggan, dan meningkat tajam hingga sekitar 17.000 pelanggan pada keterlambatan 30 hari
*   Interpretasi: Pelanggan yang sering terlambat membayar, terutama mendekati 30 hari, memiliki risiko churn yang jauh lebih tinggi

**6. Total Spend (Total Pengeluaran)**
*   Pelanggan Churn banyak ditemukan pada total pengeluaran 100–500 dengan frekuensi sekitar 8.000–8.800 pelanggan
*   Pelanggan Tidak Churn mulai muncul dominan pada total pengeluaran 500–1000 dengan frekuensi sekitar 6.200–6.400 pelanggan
*  Interpretasi: Pelanggan yang mengeluarkan biaya lebih besar cenderung lebih loyal dan tidak churn


**7. Last Interaction (Interaksi Terakhir)**
*   Pelanggan Tidak Churn berada di kisaran 8.400–8.600 pelanggan pada rentang 1–15 hari sejak interaksi terakhir
*   Setelah 15 hari, jumlah Tidak Churn turun menjadi sekitar 4.200 pelanggan
*   Pelanggan Churn tetap tinggi di kisaran 8.300–8.500 pelanggan hingga 30 hari
*   Interpretasi: Pelanggan yang sudah lama tidak berinteraksi dengan layanan memiliki kemungkinan churn yang lebih besar


"""

# Boxplot untuk melihat outlier
fig, axes = plt.subplots(2, 4, figsize=(18, 9))
axes = axes.flatten()

for i, col in enumerate(num_cols):
    df_clean = df.dropna(subset=[col, 'Churn'])
    df_clean.boxplot(column=col, by='Churn', ax=axes[i],
                     boxprops=dict(color='steelblue'),
                     medianprops=dict(color='red', linewidth=2))
    axes[i].set_title(col, fontweight='bold')
    axes[i].set_xlabel('Churn (0=Tidak, 1=Ya)')
    plt.sca(axes[i])
    plt.title(col)

for j in range(len(num_cols), len(axes)):
    axes[j].set_visible(False)

plt.suptitle('Boxplot Fitur Numerik vs Churn', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""Insight :

**1. Age**
*   Tidak Churn (0)	Churn : Median ≈ 37 tahun (Q1=29, Q3=44)
*   Churn (1) : Median ≈ 42 tahun (Q1=30, Q3=54)
*   Interprestasi : Pelanggan churn cenderung sedikit lebih tua

**2. Tenure**
*   Tidak Churn (0)	Churn : Median ≈ 33 bulan (Q1=18, Q3=47)
*   Churn (1) : Median ≈ 30 bulan (Q1=15, Q3=46)
*   Interprestasi : Pelanggan tidak churn umumnya memiliki masa berlangganan sedikit lebih lama

**3. Usage Frequency**
*   Tidak Churn (0)	Churn : Median ≈ 17 kali (Q1=10, Q3=24)
*   Churn (1) : Median ≈ 15 kali (Q1=8, Q3=23)
*   Interprestasi : Pelanggan tidak churn menggunakan layanan lebih sering

**4. Support Calls**
*   Tidak Churn (0)	Churn : Median ≈ 1 kali (Q1=0, Q3=3)
*   Churn (1) : Median ≈ 5 kali (Q1=2, Q3=8)
*   Interprestasi : Pelanggan churn melakukan panggilan dukungan jauh lebih banyak

**5. Payment Delay**
*   Tidak Churn (0)	Churn : Median ≈ 10 hari (Q1=5, Q3=15)
*   Churn (1) : Median ≈ 15 hari (Q1=7, Q3=23)
*   Interprestasi : Pelanggan churn lebih sering terlambat membayar

**6. Total Spend**
*   Tidak Churn (0)	Churn : Median ≈ 750 (Q1=625, Q3=875)
*   Churn (1) : Median ≈ 540 (Q1=315, Q3=770)
*   Interprestasi : Pelanggan tidak churn memiliki total pengeluaran lebih tinggi

**7. Last Interaction**
*   Tidak Churn (0)	Churn : Median ≈ 12 hari (Q1=6, Q3=19)
*   Churn (1) : Median ≈ 16 hari (Q1=8, Q3=23)
*   Interprestasi : Pelanggan churn cenderung lebih lama tidak berinteraksi dengan layanan

### 2.8 Eksplorasi Fitur Kategorikal
"""

cat_cols = ['Gender', 'Subscription Type', 'Contract Length']

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

for i, col in enumerate(cat_cols):
    df_clean = df.dropna(subset=[col, 'Churn'])
    churn_by_cat = df_clean.groupby(col)['Churn'].value_counts(normalize=True).unstack() * 100
    churn_by_cat.plot(kind='bar', ax=axes[i], color=['#2ecc71', '#e74c3c'],
                      alpha=0.85, edgecolor='white', width=0.7)
    axes[i].set_title(f'Churn Rate per {col}', fontweight='bold')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Persentase (%)')
    axes[i].legend(['Tidak Churn', 'Churn'], loc='upper right')
    axes[i].tick_params(axis='x', rotation=0)
    axes[i].set_ylim(0, 110)

plt.suptitle('Distribusi Churn per Fitur Kategorikal', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""Insight :

1.   **Gender** : Pelanggan perempuan memiliki tingkat churn lebih tinggi (66%) dibandingkan pelanggan laki-laki (49%)
2.   **Subscription Type** : Semua jenis langganan memiliki tingkat churn yang relatif mirip (56–58%). Paket Basic memiliki churn tertinggi (58%) dibanding tidak churn(41%)
3.   **Contract Length** : Pelanggan dengan kontrak Monthly memiliki tingkat churn tertinggi (100%), sedangkan kontrak Annual dan Quarterly memiliki tingkat churn yang jauh lebih rendah, yaitu sekitar 46%
4. Data menunjukkan seluruh pelanggan kontrak Monthly tercatat churn (100%), namun kondisi ini teridentifikasi sebagai anomali pada dataset publik Kaggle yang digunakan. Hal ini kemungkinan merupakan karakteristik bawaan dataset sintetis yang sengaja dirancang untuk tujuan pembelajaran (kaggle), sehingga temuan ini tidak dapat digeneralisasi langsung ke kondisi bisnis nyata dan perlu divalidasi menggunakan data pelanggan aktual perusahaan

#### 2.8.1 Uji Statistik Fitur Kategorikal (Chi-Square & Cramér's V)
"""

from scipy.stats import chi2_contingency
import numpy as np

def cramers_v(confusion_matrix):
    """Hitung Cramér's V dari contingency table."""
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    phi2 = chi2 / n
    r, k = confusion_matrix.shape
    phi2corr = max(0, phi2 - ((k-1)*(r-1))/(n-1))
    rcorr = r - ((r-1)**2)/(n-1)
    kcorr = k - ((k-1)**2)/(n-1)
    return np.sqrt(phi2corr / min((kcorr-1), (rcorr-1)))

cat_cols = ['Gender', 'Subscription Type', 'Contract Length']
hasil_uji = []

print('=== Uji Chi-Square & Cramér\'s V terhadap Churn ===\n')
print(f"{'Fitur':<22} {'Chi2':>10} {'p-value':>12} {'Cramér\'s V':>12} {'Kekuatan':>12} {'Signifikan':>11}")
print('─' * 82)

for col in cat_cols:
    ct = pd.crosstab(df[col], df['Churn'])
    chi2, p, dof, expected = chi2_contingency(ct)
    cv = cramers_v(ct)

    if cv < 0.1:
        kekuatan = 'Lemah'
    elif cv < 0.3:
        kekuatan = 'Sedang'
    else:
        kekuatan = 'Kuat'

    signifikan = '✅ Ya (p < 0.05)' if p < 0.05 else '❌ Tidak'
    hasil_uji.append({'Fitur': col, 'Chi2': chi2, 'p-value': p, "Cramér's V": cv, 'Kekuatan': kekuatan})
    print(f"{col:<22} {chi2:>10.2f} {p:>12.4f} {cv:>12.4f} {kekuatan:>12} {signifikan:>11}")

print('─' * 82)
print('\nInterpretasi Cramér\'s V:')
print('  < 0.10 → Asosiasi lemah')
print('  0.10 – 0.29 → Asosiasi sedang')
print('  ≥ 0.30 → Asosiasi kuat')

df_uji = pd.DataFrame(hasil_uji)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# ── Bar chart Cramér's V ──────────────────────────────
warna_bar = ['#e74c3c' if v >= 0.3 else '#f39c12' if v >= 0.1 else '#95a5a6'
             for v in df_uji["Cramér's V"]]

bars = axes[0].bar(df_uji['Fitur'], df_uji["Cramér's V"],
                   color=warna_bar, alpha=0.85, edgecolor='white', linewidth=1.5)
axes[0].axhline(y=0.1, color='#f39c12', linestyle='--', linewidth=1.2, label='Batas sedang (0.10)')
axes[0].axhline(y=0.3, color='#e74c3c', linestyle='--', linewidth=1.2, label='Batas kuat (0.30)')
axes[0].set_title("Cramér's V per Fitur Kategorikal", fontweight='bold')
axes[0].set_ylabel("Cramér's V")
axes[0].set_ylim(0, 1)
axes[0].legend(fontsize=9)
axes[0].grid(True, axis='y', alpha=0.3)

for bar, val in zip(bars, df_uji["Cramér's V"]):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                 f'{val:.3f}', ha='center', fontweight='bold', fontsize=11)

# ── Crosstab % per fitur ─────────────────────────────
for col in cat_cols:
    ct_pct = pd.crosstab(df[col], df['Churn'], normalize='index') * 100
    ct_pct.columns = ['Tidak Churn', 'Churn']
    ct_pct['Label'] = ct_pct['Churn'].apply(lambda x: f'{x:.1f}%')
    print(f'\nDistribusi Churn per {col}:')
    print(ct_pct.round(1).to_string())

axes[1].axis('off')
tabel_data = [[r['Fitur'], f"{r['Chi2']:.0f}", f"{r['p-value']:.4f}",
               f"{r['Cramér\'s V']:.3f}", r['Kekuatan']]
              for _, r in df_uji.iterrows()]
col_labels = ['Fitur', 'Chi²', 'p-value', "Cramér's V", 'Kekuatan']
tbl = axes[1].table(cellText=tabel_data, colLabels=col_labels,
                    loc='center', cellLoc='center')
tbl.auto_set_font_size(False)
tbl.set_fontsize(11)
tbl.scale(1.2, 2)
axes[1].set_title('Ringkasan Hasil Uji Statistik', fontweight='bold', pad=20)

plt.suptitle('Uji Asosiasi Fitur Kategorikal terhadap Churn', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

# Insight otomatis berdasarkan hasil uji
print('\n=== Insight Uji Statistik ===\n')
for _, row in df_uji.iterrows():
    status = 'berpengaruh signifikan' if row['p-value'] < 0.05 else 'TIDAK berpengaruh signifikan'
    print(f"• {row['Fitur']:<22}: {status} terhadap Churn "
          f"(Cramér's V = {row['Cramér\'s V']:.3f} → {row['Kekuatan']})")

"""**Insight :**


1.   Gender → Cramér's V = 0.175 (Sedang), artinya ada perbedaan pola churn antara pria dan wanita yang cukup berarti, konsisten dengan visualisasi di 2.8 yang menunjukkan wanita churn lebih tinggi (66%).
2.   Subscription Type → Cramér's V = 0.020 (Lemah), ini konfirmasi penting, meski di bar chart terlihat ada perbedaan, secara statistik jenis paket hampir tidak berpengaruh terhadap churn. Artinya insight visual di 2.8 perlu dikoreksi; perbedaan yang terlihat kemungkinan hanya kebetulan.
3. Contract Length → Cramér's V = 0.434 (Kuat), ini yang paling signifikan di antara ketiga fitur kategorik. Jenis kontrak benar-benar berpengaruh besar terhadap churn, dan ini mendukung temuan bahwa pelanggan Monthly hampir semua churn.

### 2.9 Analisis Korelasi
"""

# Heatmap korelasi fitur numerik
corr_cols = num_cols + ['Churn']
corr_matrix = df[corr_cols].dropna().corr().round(2)

plt.figure(figsize=(10, 8))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f',
            cmap='RdYlGn', center=0, vmin=-1, vmax=1,
            square=True, linewidths=0.5,
            cbar_kws={'shrink': 0.8})
plt.title('Heatmap Korelasi Fitur Numerik', fontweight='bold', fontsize=14)
plt.tight_layout()
plt.show()

# Korelasi terhadap Churn
print('\n Korelasi fitur terhadap Churn:')
churn_corr = corr_matrix['Churn'].drop('Churn').sort_values(key=abs, ascending=False)
for feat, val in churn_corr.items():
    bar = '█' * int(abs(val) * 20)
    print(f'  {feat:<20} {val:+.3f}  {bar}')

"""Insight :

1.   Support Calls (0, 57) : Cukup berpengaruh terhadap churn (sedang) → Semakin banyak panggilan ke customer support, semakin tinggi kemungkinan churn.
2.   Total Spend (-0, 43) : Cukup berpengaruh terhadap churn (sedang), karena bernilai negatif → Semakin besar pengeluaran pelanggan, semakin kecil kemungkinan churn.
3. Payment Delay (0, 31) : Sedikit berpengaruh terhadap churn (lemah) → Semakin sering terlambat membayar, semakin tinggi kemungkinan churn.
4. Age (0, 22) : Sedikit berpengaruh terhadap churn (lemah)
5. Last Interaction (0, 15) : Hampir tidak berpengaruh terhadap churn (sangat lemah)
6. Tenure (-0, 05) : Hampir tidak memiliki hubungan  dengan churn (sangat lemah)
7. Usage Frequency (-0,05) : Hampir tidak memiliki hubungan terhadap churn (sangat lemah)

### 2.10 Temuan Data Understanding

1.   Ditemukan tipe data yang belum sesuai sehingga perlu dilakukan konversi pada kolom Gender, Subscription Type, Contract Length, dan Churn
2.   Terdapat fitur CustomerID yang tidak memiliki nilai prediktif sehingga perlu dihapus
3.  Ditemukan 1 baris kosong (missing value) yang perlu ditangani dengan menghapus baris tersebut   
4.  Tidak ditemukan outlier ekstrem sehingga tidak diperlukan proses penanganan outlier
5.  Distribusi target Churn cukup seimbang (43,3% churn dan 56,7% tidak churn), sehingga tidak diperlukan SMOTE, namun hanya perlu menambahkan class_weight='balanced' pada saat melakukan modelling
6.   Rentang nilai antar fitur numerik berbeda cukup jauh sehingga diperlukan feature scaling
7. Fitur kategorikal perlu diubah ke format numerik melalui encoding sebelum pemodelan

---
## 3. DATA PREPARATION

Step :

1.   Penyelesaian missing values  (hapus missing)
2.   Drop baris yang tidak relevan untuk modelling
3.   Konversi tipe data
4.   Encoding fitur kategorik
5.   Export dataset bersih
6.   Pisahkan fitur x dan y
7.   Split data train dan data test
8.   Feature scalling
9.   Pengecekan multikolinearitas (VIF)

### 3.1 Missing Values
"""

df = df.dropna()
print(f'Jumlah baris setelah drop missing values: {df.shape[0]:,}')

"""### 3.2 Drop Baris Tidak Relevan"""

df = df.drop(columns=['CustomerID'], errors='ignore')
print(' Kolom CustomerID berhasil dihapus')

df.head()

"""### 3.3 Konversi Tipe Data Churn"""

df['Churn'] = df['Churn'].astype(int)

print('\nTipe data setelah perubahan:')
print(df.dtypes)

print(df['Contract Length'].unique())

"""### 3.4 Encoding Fitur Kategorik"""

from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Pisah berdasarkan jenis fitur
nominal_cols = ['Gender', 'Subscription Type']   # tidak ada urutan → One-Hot
ordinal_col  = 'Contract Length'                  # ada urutan bisnis → Label

# ── One-Hot Encoding untuk fitur nominal ──────────────────
ohe = OneHotEncoder(drop='first', sparse_output=False)
ohe_result = ohe.fit_transform(df[nominal_cols])
ohe_cols   = ohe.get_feature_names_out(nominal_cols)
df_ohe     = pd.DataFrame(ohe_result, columns=ohe_cols, index=df.index)

print('Kolom hasil One-Hot Encoding:')
print(list(ohe_cols))

# ── Label Encoding untuk Contract Length (ordinal) ────────
urutan_kontrak = {'Monthly': 0, 'Quarterly': 1, 'Annual': 2}
df['Contract Length'] = df['Contract Length'].map(urutan_kontrak)

print('\nMapping Contract Length (ordinal):')
for label, val in urutan_kontrak.items():
    print(f'  {val} = {label}')

# ── Gabungkan & hapus kolom asli ──────────────────────────
df = df.drop(columns=nominal_cols)
df = pd.concat([df, df_ohe], axis=1)

print(f'\nShape setelah encoding: {df.shape}')
print(f'Kolom sekarang: {list(df.columns)}')
df.head()

"""Insight :

1. Gender sudah berhasil di encoding
- `Gender = 1` → Male
- `Gender = 0` → Female

2. Subscription Type
- `Subscription Type = 0` → Basic
- `Subscription Type = 1` → Standard
- `Subscription Type = 2` → Premium

3.  Contract Length
- `Contract Length = 0` → Monthly
- `Contract Length = 1` → Quarterly
- `Contract Length = 2` → Annual

### 3.5 Export Dataset Bersih
"""

df.to_csv('/content/drive/MyDrive/Customer Churn_Data Mining/clean_customer_churn.csv', index=False)
print(f'Dataset bersih berhasil diekspor!')
print(f'Shape: {df.shape[0]:,} baris × {df.shape[1]} kolom')
print(f'Kolom: {list(df.columns)}')

"""### 3.6 Pisahkan Fitur (X) dan Target (y)"""

X = df.drop(columns=['Churn'])
y = df['Churn']

print(f'Shape X (fitur): {X.shape}')
print(f'Shape y (target): {y.shape}')
print(f'Fitur yang digunakan: {list(X.columns)}')

"""Insight :

1.   Shape X (fitur) → Data Input (440.832, 10) : Berarti mempunyai 440.832 data dan 10 fitur yang akan digunakan
    

2.   Shape Y (target) → Jawaban yang ingin diprediksi (440.832,) : Berarti mempunyai 440.832 nilai target dan memiliki 1 kolom target, yaitu Churn

### 3.7 Split Data Train dan Test
"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(f'Data Training : {X_train.shape[0]:,} baris')
print(f'Data Testing  : {X_test.shape[0]:,} baris')

"""Insight :

Dataset yang berjumlah 440.832 data dibagi menjadi :
1.   Data training sebanyak  352.665 (80%), digunakan untuk melatih model dalam mengenali pola churn pelanggan
2.   Data testing sebanyak 88.167 (20%), digunakan untuk mengevaluasi kemampuan model dalam memprediksi status churn pada data yang belum pernah digunakan selama proses pelatihan

### 3.8 Feature Scaling
"""

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(' Feature scaling selesai!')

pd.DataFrame(X_train_scaled, columns=X.columns).head()

"""Insight :

Menunjukkan bahwa seluruh fitur telah berada pada skala yang seragam dengan nilai yang berpusat di sekitar 0. Nilai positif menunjukkan karakteristik di atas rata-rata, sedangkan nilai negatif menunjukkan karakteristik di bawah rata-rata

#### 3.8.1 Pengecekan Multikolinearitas (VIF)
"""

from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

# Gunakan data training yang sudah di-scale
X_train_df = pd.DataFrame(X_train_scaled, columns=X.columns)

# Hitung VIF untuk setiap fitur
vif_data = pd.DataFrame()
vif_data['Fitur'] = X_train_df.columns
vif_data['VIF']   = [variance_inflation_factor(X_train_df.values, i)
                     for i in range(X_train_df.shape[1])]
vif_data = vif_data.sort_values('VIF', ascending=False).reset_index(drop=True)

# Tambahkan kategori
def kategori_vif(v):
    if v < 5:   return '✅ Aman'
    elif v < 10: return '⚠️ Moderat'
    else:        return '❌ Tinggi'

vif_data['Status'] = vif_data['VIF'].apply(kategori_vif)

print('=== Variance Inflation Factor (VIF) ===')
print(vif_data.round(2).to_string(index=False))
print()
print('Interpretasi:')
print('  VIF < 5   → Aman, tidak ada multikolinearitas')
print('  VIF 5–10  → Moderat, perlu diwaspadai')
print('  VIF > 10  → Tinggi, ada multikolinearitas serius')

# Visualisasi VIF
plt.figure(figsize=(9, 5))
colors = ['#2ecc71' if v < 5 else '#f39c12' if v < 10 else '#e74c3c'
          for v in vif_data['VIF']]

bars = plt.barh(vif_data['Fitur'], vif_data['VIF'],
                color=colors, alpha=0.85, edgecolor='white')
plt.axvline(x=5,  color='#f39c12', linestyle='--', linewidth=1.5, label='Batas moderat (5)')
plt.axvline(x=10, color='#e74c3c', linestyle='--', linewidth=1.5, label='Batas tinggi (10)')
plt.xlabel('VIF Score')
plt.title('Variance Inflation Factor per Fitur', fontweight='bold')
plt.legend()
plt.tight_layout()
plt.show()

"""**Insight :**
1. Subscription Type_Premium & Standard → VIF tertinggi (~1.5), wajar karena
  keduanya berasal dari fitur yang sama (hasil One-Hot Encoding), namun
  masih jauh di bawah batas aman
2. Seluruh fitur lainnya → VIF ~1.0, mendekati nilai ideal (VIF=1 berarti
  tidak ada korelasi sama sekali antar fitur)
"""

# Insight otomatis
masalah = vif_data[vif_data['VIF'] >= 5]
aman    = vif_data[vif_data['VIF'] <  5]

print('=== Insight Multikolinearitas ===\n')
if len(masalah) == 0:
    print('Seluruh fitur memiliki VIF < 5 → tidak ada multikolinearitas.')
    print('Asumsi Logistic Regression terpenuhi, model dapat dilanjutkan.')
else:
    print(f'Ditemukan {len(masalah)} fitur dengan VIF ≥ 5:')
    for _, row in masalah.iterrows():
        print(f'  • {row["Fitur"]:<25} VIF = {row["VIF"]:.2f} ({row["Status"]})')
    print('\nFitur yang aman:')
    for _, row in aman.iterrows():
        print(f'  • {row["Fitur"]:<25} VIF = {row["VIF"]:.2f}')

"""### 3.9 Hasil Data Preparation

* Data yang memiliki missing values telah dihapus menggunakan  dropna()
* Kolom CustomerID dihapus karena hanya berfungsi sebagai identitas pelanggan
* Variabel kategorikal telah diubah ke bentuk numerik (encoding) agar dapat diproses oleh algoritma klasifikasi
* Variabel yang diencoding:
  * Gender
  * Subscription Type
  * Contract Length
* Dataset setelah dibersihkan terdiri dari 440.832 baris data
* Jumlah atribut prediktor (fitur) yang digunakan sebanyak 10 atribut
* Variabel target yang diprediksi adalah Churn
* Atribut yang digunakan dalam project:
  * Age
  * Gender
  * Tenure
  * Usage Frequency
  * Support Calls
  * Payment Delay
  * Subscription Type
  * Contract Length
  * Total Spend
  * Last Interaction
* Variabel target Churn terdiri dari:

  * 0 = Tidak Churn
  * 1 = Churn
* Dataset dibagi menjadi:

  * 352.665 data training (80%)
  * 88.167 data testing (20%)

Pemilihan Algoritma : **Logistic Regression**

1.   Cepat dan ringan : Pada tahap Data Preparation dataset yang dipakai sudah berjumlah ±440.000 baris, model yang berat (Random Forest, SVM, Neural Network) akan lebih mahal dilatih pada skala ini, sementara Logistic Regression tetap efisien
2.   Mudah diinterpretasi & tidak black box : Merujuk ke Business Understanding di mana tujuan akhirnya bukan sekadar memprediksi, tapi memberi dasar untuk strategi retensi (promo, peningkatan layanan, pendekatan personal). Koefisien Logistic Regression bisa langsung menunjukkan fitur mana yang mendorong/menahan churn, sehingga hasilnya bisa dijelaskan ke tim bisnis, bukan cuma angka prediksi tanpa alasan
3.  Tidak butuh tuning rumit : Mendukung efisiensi yang sama dengan poin pertama, terutama karena fokus proyek ada di pemenuhan target Recall dan AUC-ROC, bukan eksplorasi hyperparameter yang panjang
4.  Cocok untuk hubungan linear, merujuk ke temuan Data Understanding pada analisis korelasi, di mana fitur seperti Support Calls (0,57), Total Spend (-0,43), dan Payment Delay (0,31) menunjukkan hubungan yang cukup konsisten/monotonic terhadap churn, bukan pola non-linear kompleks — kondisi yang pas dengan asumsi dasar Logistic Regression
5.   Hasil lebih stabil dan realistis : Merujuk ke Data Understanding yang menemukan tidak ada outlier ekstrem dan distribusi data cukup normal/seimbang, sehingga risiko overfitting seperti yang biasa terjadi pada Decision Tree/Random Forest pada dataset bersih semacam ini bisa ditekan dengan model yang lebih sederhana
6.   Pada tahap Data Preparation fitur numerik sudah melalui StandardScaler dan distribusi target Churn relatif seimbang (43,3% vs 56,7%) tanpa perlu SMOTE, kondisi ini juga sudah sesuai dengan kebutuhan Logistic Regression yang sensitif terhadap skala fitur dan tidak memerlukan penyeimbangan data yang rumit

---
## 4. Modelling

 Tujuan : Mengubah data menjadi model prediktif yang bisa membedakan pelanggan churn vs tidak churn berdasarkan pola yang dipelajari dari data training
"""

lr_model = LogisticRegression(random_state=42, max_iter=1000, class_weight='balanced')
lr_model.fit(X_train_scaled, y_train)

y_pred_lr = lr_model.predict(X_test_scaled)
y_prob_lr = lr_model.predict_proba(X_test_scaled)[:, 1]

print('✅ Logistic Regression selesai dilatih!')

"""Menggunakan **class_weight='balanced'** sebagai pengganti SMOTE, **class_weight='balanced'** digunakan untuk mengantisipasi terjadinya data imbalanced dan juga penggunaanya lebih ringan dibanding menggunakan SMOTE

Dapat diinterpretasikan dengan menggunakan feature importance dan koefisien

### 4.1 Cross Validation
"""

from sklearn.model_selection import cross_val_score

cv_recall = cross_val_score(lr_model, X_train_scaled, y_train, cv=5, scoring='recall')
cv_auc = cross_val_score(lr_model, X_train_scaled, y_train, cv=5, scoring='roc_auc')

print(f'Cross-Val Recall  : {cv_recall.mean():.4f} ± {cv_recall.std():.4f}')
print(f'Cross-Val AUC-ROC : {cv_auc.mean():.4f} ± {cv_auc.std():.4f}')

"""Insight :

1.   Recall 0.83 ± 0.002, artinya dari setiap 100 pelanggan yang benar-benar akan churn, model berhasil mendeteksi sekitar 83 orang. Angka ini konsisten di semua pengujian, selisihnya hanya 0,2%,jadi bukan kebetulan dari satu percobaan saja
2.   AUC-ROC 0.93 ± 0.001, artinya model punya kemampuan membedakan pelanggan yang akan churn vs tidak churn dengan tingkat keyakinan 93%. Nilai ini juga sangat stabil dengan selisih hanya 0,1% antar pengujian


Model sudah terbukti handal. Dari 100 pelanggan yang berisiko pergi, 83 di antaranya bisa diidentifikasi lebih awal, sehingga tim bisnis punya cukup waktu untuk melakukan intervensi (promo, pendekatan personal, peningkatan layanan) sebelum pelanggan tersebut benar-benar berhenti berlangganan.

### 4.2 Threshold Tuning

Threshold tuning adalah proses mencari dan menyesuaikan batas keputusan yang paling optimal sesuai tujuan yang ingin dicapai -> "menurunkan standar" untuk memprediksi churn supaya model lebih sensitif menangkap pelanggan yang berisiko pergi, sesuai prioritas bisnis
"""

# Threshold Tuning - menurunkan threshold untuk meningkatkan Recall
threshold = 0.4
y_pred_custom = (y_prob_lr >= threshold).astype(int)

# Evaluasi dengan threshold baru
rec_custom = recall_score(y_test, y_pred_custom)
auc_custom = roc_auc_score(y_test, y_prob_lr)

print('Perbandingan Threshold:')
print(f'{"":20} {"Default (0.5)":>15} {"Custom (0.4)":>15}')
print(f'{"Recall":20} {recall_score(y_test, y_pred_lr):>15.4f} {rec_custom:>15.4f}')
print(f'{"AUC-ROC":20} {roc_auc_score(y_test, y_prob_lr):>15.4f} {auc_custom:>15.4f}')

"""**Insight :**

1.   Hasil perbandingan menunjukkan bahwa penurunan threshold dari 0.5 menjadi 0.4 berhasil meningkatkan nilai recall dari 82,98% menjadi 86,68%, sementara nilai AUC-ROC tetap sebesar 0.9280
2.   Peningkatan recall ini berarti model menjadi lebih baik dalam mengidentifikasi kelas positif. Dengan threshold 0.4, model berhasil mendeteksi sekitar 86,68% dari seluruh data positif, sedangkan pada threshold 0.5 hanya mampu mendeteksi 82,98%. Artinya terdapat lebih sedikit False Negative, yaitu kasus positif yang salah diprediksi sebagai negatif. Dari 100 pelanggan yang benar-benar akan churn, model kini berhasil mendeteksi 87 orang, bertambah 4 orang dibanding threshold default. Keempat orang inilah yang sebelumnya "lolos" tanpa terdeteksi dan tidak mendapat intervensi.
3. Nilai AUC-ROC tetap sebesar 0.928 pada semua threshold karena AUC-ROC mengukur kemampuan model membedakan kelas positif dan negatif berdasarkan seluruh kemungkinan threshold, bukan hanya satu threshold tertentu.

#### 4.2.1 Evaluasi Visual Perbandingan Threshold

Semakin rendah threshold → model makin "sensitif" → lebih banyak pelanggan churn yang terdeteksi (Recall naik) → tapi lebih banyak juga yang salah diprediksi churn (Precision turun).
"""

from sklearn.metrics import precision_score, f1_score

thresholds = [0.3, 0.4, 0.5, 0.6, 0.7]
hasil = []

for t in thresholds:
    y_pred_t = (y_prob_lr >= t).astype(int)
    hasil.append({
        'Threshold' : t,
        'Recall'    : recall_score(y_test, y_pred_t),
        'Precision' : precision_score(y_test, y_pred_t),
        'F1-Score'  : f1_score(y_test, y_pred_t),
        'AUC-ROC'   : roc_auc_score(y_test, y_prob_lr)
    })

df_thresh = pd.DataFrame(hasil)

print('=== Perbandingan Metrik per Threshold ===')
print(df_thresh.round(4).to_string(index=False))

"""**Insight :**

Semakin kecil threshold, model akan semakin mudah mengklasifikasikan suatu data sebagai kelas positif. Sebaliknya, semakin besar threshold, model akan semakin ketat dalam memberikan prediksi positif.

**Insight per threshold :**
1. Threshold 0.3

*  Recall tertinggi (90,01%), artinya model mampu mendeteksi hampir seluruh data positif
*   Namun, precision hanya 82,48%, menunjukkan cukup banyak prediksi positif yang sebenarnya negatif (False Positive)
*   Cocok jika prioritas utama adalah tidak melewatkan kasus positif

2. Threshold 0.4
*  Recall sedikit menurun menjadi 86,68%, tetapi precision meningkat menjadi 86,66%
*  Menghasilkan F1-Score tertinggi (86,67%), yang berarti keseimbangan antara recall dan precision paling baik
* Threshold ini memberikan trade-off yang optimal antara kemampuan mendeteksi kasus positif dan mengurangi kesalahan prediksi positif

3. Threshold 0.5 (Default)
*  Precision meningkat menjadi 90,16%, sehingga prediksi positif lebih akurat
*  Recall turun menjadi 82,98%, sehingga lebih banyak kasus positif yang terlewat
*  Cocok jika False Positive ingin dikurangi

4. Threshold 0.6
*  Precision semakin tinggi (93,18%)
*  Recall turun menjadi 79,03%
*  Model menjadi semakin konservatif dalam memberikan prediksi positif

5. Threshold 0.7
*  Precision mencapai nilai tertinggi (95,70%)
*  Namun recall turun cukup besar menjadi 74,21%
*  Banyak kasus positif yang gagal terdeteksi sehingga kurang cocok apabila tujuan utama adalah mendeteksi seluruh kasus positif

**Pola yang terlihat :**

Dari tabel terlihat adanya trade-off antara recall dan precision.

* Ketika threshold dinaikkan dari 0.3 menjadi 0.7:
- Recall terus menurun (90,01% → 74,21%)
- Precision terus meningkat (82,48% → 95,70%)

Hal ini terjadi karena threshold yang lebih tinggi membuat model hanya memberikan prediksi positif pada data dengan probabilitas yang sangat tinggi. Akibatnya, prediksi positif menjadi lebih akurat, tetapi semakin banyak data positif yang tidak terdeteksi.

Sebaliknya, threshold yang lebih rendah membuat model lebih mudah mengklasifikasikan data sebagai positif, sehingga recall meningkat, namun risiko False Positive juga bertambah.

#### 4.2.2 Visualisasi Evaluasi Thresold Tuning
"""

fig, axes = plt.subplots(1, 2, figsize=(15, 6))

# Plot 1 — Line chart semua metrik
for metrik, warna in zip(['Recall', 'Precision', 'F1-Score'],
                          ['#e74c3c', '#3498db', '#2ecc71']):
    axes[0].plot(df_thresh['Threshold'], df_thresh[metrik],
                 marker='o', linewidth=2, color=warna, label=metrik)

axes[0].axvline(x=0.4, color='gray', linestyle='--', linewidth=1.5, label='Threshold dipilih (0.4)')
axes[0].axhline(y=0.75, color='#e74c3c', linestyle=':', linewidth=1, alpha=0.6, label='Target Recall (0.75)')
axes[0].set_xlabel('Threshold')
axes[0].set_ylabel('Skor')
axes[0].set_title('Perubahan Metrik per Threshold', fontweight='bold')
axes[0].legend()
axes[0].grid(True, alpha=0.3)
axes[0].set_ylim(0, 1.05)

# Plot 2 — Bar chart perbandingan threshold 0.5 vs 0.4
metrik_compare = ['Recall', 'Precision', 'F1-Score']
val_05 = df_thresh[df_thresh['Threshold'] == 0.5][metrik_compare].values[0]
val_04 = df_thresh[df_thresh['Threshold'] == 0.4][metrik_compare].values[0]

x = range(len(metrik_compare))
width = 0.35

bars1 = axes[1].bar([i - width/2 for i in x], val_05, width,
                     label='Threshold 0.5 (Default)', color='#95a5a6', alpha=0.85)
bars2 = axes[1].bar([i + width/2 for i in x], val_04, width,
                     label='Threshold 0.4 (Dipilih)', color='#e74c3c', alpha=0.85)

axes[1].set_xticks(list(x))
axes[1].set_xticklabels(metrik_compare)
axes[1].set_ylabel('Skor')
axes[1].set_title('Default (0.5) vs Threshold Dipilih (0.4)', fontweight='bold')
axes[1].legend()
axes[1].set_ylim(0, 1.1)
axes[1].grid(True, axis='y', alpha=0.3)

for bar in bars1:
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                 f'{bar.get_height():.2f}', ha='center', fontsize=9)
for bar in bars2:
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                 f'{bar.get_height():.2f}', ha='center', fontsize=9)

plt.suptitle('Evaluasi Threshold Tuning', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""**Bisa disimpulkan**

Berdasarkan hasil evaluasi threshold tuning, threshold 0.4 dipilih sebagai threshold terbaik karena memberikan keseimbangan paling optimal antara recall, precision, dan F1-score. Dibandingkan threshold default 0.5, penggunaan threshold 0.4 meningkatkan recall dari 82,98% menjadi 86,68%, sehingga model mampu mendeteksi lebih banyak kasus positif. Meskipun precision sedikit menurun dari 90,16% menjadi 86,66%, nilai F1-score justru meningkat menjadi 86,67%, yang menunjukkan performa model secara keseluruhan lebih seimbang. Oleh karena itu, threshold 0.4 dipilih karena lebih efektif dalam meminimalkan kasus positif yang terlewat (false negative) tanpa mengorbankan performa model secara signifikan.

#### 4.2.3 Insight Evaluasi Thresold Tuning
"""

rec_05 = df_thresh[df_thresh['Threshold']==0.5]['Recall'].values[0]
rec_04 = df_thresh[df_thresh['Threshold']==0.4]['Recall'].values[0]
print(f'\nInsight:')
print(f'Menurunkan threshold dari 0.5 → 0.4 meningkatkan Recall dari {rec_05:.2f} → {rec_04:.2f}')
print(f'Trade-off: Precision sedikit turun, namun sesuai prioritas project yaitu mendeteksi sebanyak mungkin pelanggan churn')

"""Untuk project retensi pelanggan seperti ini, lebih baik salah tangkap pelanggan loyal daripada melewatkan pelanggan yang mau pergi,makanya threshold 0.4 lebih cocok.

## 5. Evaluation

### 5.1 Fungsi Evaluasi Metrik
"""

def evaluate_model(name, y_test, y_pred, y_prob):
    rec = recall_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob)

    print(f'\n {name}')
    print(f'Recall    : {rec:.4f}')
    print(f'AUC-ROC   : {auc:.4f}')
    print('\nClassification Report:')
    print(classification_report(y_test, y_pred, target_names=['Tidak Churn', 'Churn']))

    return {'Recall': rec, 'AUC-ROC': auc}

"""### 5.2 Evaluasi Logistic Regression"""

scores_lr = evaluate_model('Logistic Regression', y_test, y_pred_custom, y_prob_lr)

"""**Hasil Logistic Regression :**

1. Recall 0.87, dari setiap 100 pelanggan yang benar-benar akan churn, model berhasil mengidentifikasi 87 orang. Artinya tim bisnis punya kesempatan untuk mengintervensi (promo, diskon, pendekatan personal) kepada 87% pelanggan berisiko sebelum mereka benar-benar pergi.
2. AUC-ROC 0.93, model punya tingkat keyakinan 93% dalam membedakan mana pelanggan yang akan churn dan mana yang tidak, jauh di atas standar minimum yang ditetapkan (85%).

**Hasil Classification Report:**

1. Kelas "Tidak Churn" (50.000 pelanggan):
* Precision 0.83, dari semua yang diprediksi "tidak churn", 83% benar-benar tidak churn
* Recall 0.83, dari semua pelanggan yang sebenarnya tidak churn, 83% berhasil terdeteksi dengan benar
* F1-Score 0.83, keseimbangan precision dan recall untuk kelas ini

2. Kelas "Churn" (38.167 pelanggan):
* Precision 0.87, dari semua yang diprediksi "churn", 87% benar-benar churn
* Recall 0.87, dari semua pelanggan yang sebenarnya churn, 87% berhasil terdeteksi
* F1-Score 0.87, keseimbangan precision dan recall untuk kelas ini



Classification Report ditampilkan sebagai informasi pendukung yang mencakup seluruh metrik per kelas. Namun kriteria utama yang ditetapkan di Business Understanding tetap Recall dan AUC-ROC, dan keduanya telah tercapai.

### 5.3 Export Hasil Prediksi
"""

# Export hasil prediksi model untuk dashboard prediktif
df_result = X_test.copy()
df_result['Actual_Churn'] = y_test.values
df_result['Predicted_Churn'] = y_pred_custom
df_result['Churn_Probability'] = y_prob_lr.round(4)

# Tambahkan label teks supaya mudah dibaca di dashboard
df_result['Status_Aktual'] = df_result['Actual_Churn'].map({0: 'Tidak Churn', 1: 'Churn'})
df_result['Status_Prediksi'] = df_result['Predicted_Churn'].map({0: 'Tidak Churn', 1: 'Churn'})
df_result['Risiko'] = pd.cut(df_result['Churn_Probability'],
                              bins=[0, 0.4, 0.7, 1.0],
                              labels=['Rendah', 'Sedang', 'Tinggi'])

df_result.to_csv('/content/drive/MyDrive/Customer Churn_Data Mining/prediction_result.csv', index=False)
print(f'Hasil prediksi berhasil diekspor!')
print(f'Shape: {df_result.shape[0]:,} baris × {df_result.shape[1]} kolom')
print(df_result[['Churn_Probability', 'Status_Aktual', 'Status_Prediksi', 'Risiko']].head())

"""### 5.4 Confusion Matrix"""

cm = confusion_matrix(y_test, y_pred_custom)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Tidak Churn', 'Churn'],
            yticklabels=['Tidak Churn', 'Churn'])
plt.title('Confusion Matrix - Logistic Regression')
plt.xlabel('Prediksi')
plt.ylabel('Aktual')
plt.tight_layout()
plt.show()

"""**Insight :**

*   TN (43.340) → Pelanggan tidak churn, diprediksi tidak churn
*   FP (6.660) → Pelanggan tidak churn, tapi diprediksi churn
*    FN (6.669) → Pelanggan churn, tapi diprediksi tidak churn  (paling berbahaya)
*  TP (31.498) → Pelanggan churn, diprediksi churn

Model berhasil menangkap 31.498 dari 38.167 pelanggan yang benar-benar churn (Recall ≈ 87%), masih ada 6.669 pelanggan churn yang terlewat (FN). Di sisi lain, ada 6.660 pelanggan loyal yang salah diprediksi churn (FP).

### 5.4b Analisis Error — False Negative & False Positive
"""

# Pisahkan FN dan FP dari hasil prediksi
df_eval = X_test.copy()
df_eval['Actual']      = y_test.values
df_eval['Predicted']   = y_pred_custom
df_eval['Probability'] = y_prob_lr.round(4)

fn_df = df_eval[(df_eval['Actual'] == 1) & (df_eval['Predicted'] == 0)]  # Churn tapi tidak terdeteksi
fp_df = df_eval[(df_eval['Actual'] == 0) & (df_eval['Predicted'] == 1)]  # Tidak churn tapi diprediksi churn

print(f'Total False Negative (FN) : {len(fn_df):,} pelanggan — churn tapi lolos deteksi')
print(f'Total False Positive  (FP) : {len(fp_df):,} pelanggan — loyal tapi diprediksi churn')

# Profil rata-rata FN vs pelanggan churn yang benar terdeteksi (TP)
tp_df = df_eval[(df_eval['Actual'] == 1) & (df_eval['Predicted'] == 1)]

fitur_analisis = ['Support Calls', 'Payment Delay', 'Total Spend',
                  'Tenure', 'Usage Frequency', 'Last Interaction']

profil_error = pd.DataFrame({
    'TP (Terdeteksi)'    : tp_df[fitur_analisis].mean(),
    'FN (Terlewat)'      : fn_df[fitur_analisis].mean(),
    'Selisih'            : fn_df[fitur_analisis].mean() - tp_df[fitur_analisis].mean()
}).round(2)

print('=== Profil TP vs FN (Pelanggan Churn) ===')
print(profil_error.to_string())

# Visualisasi perbandingan profil TP vs FN
fig, axes = plt.subplots(2, 3, figsize=(16, 10))
axes = axes.flatten()

for i, fitur in enumerate(fitur_analisis):
    val_tp = tp_df[fitur].mean()
    val_fn = fn_df[fitur].mean()

    bars = axes[i].bar(['TP\n(Terdeteksi)', 'FN\n(Terlewat)'],
                        [val_tp, val_fn],
                        color=['#2ecc71', '#e74c3c'],
                        alpha=0.85, edgecolor='white', linewidth=1.5)
    axes[i].set_title(f'{fitur}', fontweight='bold')
    axes[i].set_ylabel('Rata-rata')

    for bar, val in zip(bars, [val_tp, val_fn]):
        axes[i].text(bar.get_x() + bar.get_width()/2,
                     bar.get_height() + 0.1,
                     f'{val:.1f}', ha='center', fontweight='bold', fontsize=11)

plt.suptitle('Profil Pelanggan Churn: Terdeteksi (TP) vs Terlewat (FN)',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""**Insight :**
Pelanggan FN (yang terlewat) punya profil mirip pelanggan loyal:

1. Support Calls jauh lebih rendah (1.7 vs 5.6) → inilah alasan utama model gagal mendeteksi mereka. Model "belajar" bahwa banyak komplain = churn, tapi pelanggan ini churn tanpa banyak komplain
2. Payment Delay lebih rendah (11.3 vs 15.7) → pembayaran mereka relatif tepat waktu, sehingga tidak terlihat berisiko
3. Total Spend jauh lebih tinggi (733.6 vs 513.7) → mereka justru pelanggan dengan pengeluaran besar, yang biasanya diasosiasikan loyal

Yang hampir tidak berbeda:
1. Tenure (30.6 vs 31.4) → hampir sama
2. Usage Frequency (15.4 vs 15.8) → hampir sama
3. Last Interaction (15.9 vs 13.5) → perbedaan kecil


"""

# Distribusi probabilitas FN — seberapa "yakin" model bahwa mereka tidak churn?
plt.figure(figsize=(10, 5))
plt.hist(fn_df['Probability'], bins=30, color='#e74c3c', alpha=0.8, edgecolor='white')
plt.axvline(x=0.4, color='black', linestyle='--', linewidth=1.5, label='Threshold (0.4)')
plt.title('Distribusi Probabilitas Churn pada Pelanggan FN\n(Churn Nyata yang Tidak Terdeteksi)',
          fontweight='bold')
plt.xlabel('Probabilitas Churn Prediksi')
plt.ylabel('Jumlah Pelanggan')
plt.legend()
plt.tight_layout()
plt.show()

print(f'\nRata-rata probabilitas FN : {fn_df["Probability"].mean():.4f}')
print(f'Median probabilitas FN    : {fn_df["Probability"].median():.4f}')
print(f'Maks probabilitas FN      : {fn_df["Probability"].max():.4f}')

"""**Insight :** Distribusi probabilitas pelanggan FN yang tersebar merata hingga mendekati 0.00 menunjukkan bahwa kesalahan deteksi ini bukan sekadar masalah threshold, melainkan keterbatasan fitur yang tersedia. Model secara fundamental tidak memiliki cukup sinyal untuk mengenali pelanggan ini sebagai berisiko churn. Solusi jangka panjang yang disarankan adalah menambahkan fitur baru seperti skor kepuasan pelanggan (NPS), data interaksi aplikasi, atau riwayat keluhan tertulis yang dapat menangkap alasan churn yang tidak terlihat dari data transaksi saja."
"""

# Insight otomatis berdasarkan selisih profil
print('\n=== Insight: Mengapa Pelanggan FN Sulit Terdeteksi? ===\n')

for fitur in fitur_analisis:
    val_tp = tp_df[fitur].mean()
    val_fn = fn_df[fitur].mean()
    selisih = val_fn - val_tp
    arah = 'lebih tinggi' if selisih > 0 else 'lebih rendah'
    print(f'• {fitur:<20}: FN {arah} ({val_fn:.1f} vs TP {val_tp:.1f}, selisih {abs(selisih):.1f})')

"""### 5.5 Evaluasi Model"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

recall_val = recall_score(y_test, y_pred_custom)
auc_val = roc_auc_score(y_test, y_prob_lr)

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# ── 1. BAR CHART ──────────────────────────────────────────
metrics = ['Recall', 'AUC-ROC']
values  = [recall_val, auc_val]
targets = [0.75, 0.85]
colors  = ['#2ecc71', '#3498db']

bars = axes[0].bar(metrics, values, color=colors, alpha=0.85, width=0.4)
axes[0].axhline(y=0.75, color='#e74c3c', linestyle='--', linewidth=1.5, label='Target Recall (0.75)')
axes[0].axhline(y=0.85, color='#e67e22', linestyle='--', linewidth=1.5, label='Target AUC-ROC (0.85)')
axes[0].set_ylim(0, 1.15)
axes[0].set_ylabel('Skor')
axes[0].set_title('Performa Model vs Target Kriteria Sukses', fontweight='bold')
axes[0].legend(fontsize=9)
axes[0].grid(True, axis='y', alpha=0.3)

for bar, val, target in zip(bars, values, targets):
    status = '✅ TERCAPAI' if val >= target else '❌ BELUM'
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.02,
                 f'{val:.2f}\n{status}', ha='center', fontweight='bold', fontsize=10)

# ── 2. GAUGE CHART ────────────────────────────────────────
def draw_gauge(ax, value, title, target, color):
    ax.set_xlim(-1.3, 1.3)
    ax.set_ylim(-0.3, 1.3)
    ax.axis('off')

    # Background arc (abu-abu)
    theta = np.linspace(np.pi, 0, 200)
    ax.plot(np.cos(theta), np.sin(theta), color='#ecf0f1', linewidth=20, solid_capstyle='round')

    # Value arc
    theta_val = np.linspace(np.pi, np.pi - (value * np.pi), 200)
    ax.plot(np.cos(theta_val), np.sin(theta_val), color=color, linewidth=20, solid_capstyle='round')

    # Target marker
    theta_target = np.pi - (target * np.pi)
    ax.plot([0.75 * np.cos(theta_target)], [0.75 * np.sin(theta_target)],
            marker='v', color='#e74c3c', markersize=12, zorder=5)

    # Label angka di tengah
    ax.text(0, 0.15, f'{value:.2f}', ha='center', va='center',
            fontsize=28, fontweight='bold', color=color)
    ax.text(0, -0.05, f'Target: {target}', ha='center', va='center',
            fontsize=11, color='gray')
    status = '✅ TERCAPAI' if value >= target else '❌ BELUM'
    ax.text(0, -0.22, status, ha='center', va='center',
            fontsize=11, fontweight='bold', color='#27ae60' if value >= target else '#e74c3c')
    ax.set_title(title, fontweight='bold', fontsize=13, pad=10)

draw_gauge(axes[1], auc_val, 'AUC-ROC', 0.85, '#3498db')

plt.suptitle('Ringkasan Performa Model Logistic Regression', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

"""Insight :

1.   Bar Chart (kiri) — Performa vs Target:


*   Bar hijau Recall 0.87 sudah melewati garis merah putus-putus (target 0.75, artinya dari 100 pelanggan yang benar-benar akan churn, 87 orang berhasil terdeteksi oleh model untuk diintervensi lebih awal)
*   Bar biru AUC-ROC 0.93 sudah melewati garis oranye putus-putus (target 0.85), artinya model punya tingkat keyakinan 93% dalam membedakan pelanggan yang akan churn vs yang tidak


2.   Gauge Chart (kanan) — Speedometer AUC-ROC:


*   Tanda segitiga merah adalah batas minimum yang harus dicapai (0.85). Warna biru sudah melewati tanda merah tersebut dan hampir penuh, artinya model bekerja jauh di atas standar minimum yang ditetapkan. Semakin jarum mengarah ke kanan, semakin baik performa model.

### 5.6 Interpretasi Logistic Regression (Koefisien)
"""

coef_df = pd.DataFrame({
    'Fitur': X.columns,
    'Koefisien': lr_model.coef_[0]
}).sort_values('Koefisien', key=abs, ascending=False)

print('Koefisien Logistic Regression:')
print(coef_df.to_string(index=False))

plt.figure(figsize=(8, 5))
colors = ['#F44336' if c > 0 else '#2196F3' for c in coef_df['Koefisien']]
sns.barplot(x='Koefisien', y='Fitur', data=coef_df, palette=colors)
plt.title('Koefisien Logistic Regression\n(Merah = Meningkatkan Churn, Biru = Menurunkan Churn)')
plt.axvline(0, color='black', linewidth=0.8)
plt.tight_layout()
plt.show()

"""Insight Berdasarkan Koefisien Logistic Regression pada Setiap Fitur:

**Faktor yang Meningkatkan Churn (Merah):**
* Support Calls (2.1), faktor paling dominan. Semakin sering pelanggan menghubungi customer support, semakin tinggi risiko churn. Ini mengindikasikan pelanggan yang banyak komplain cenderung tidak puas dan berpotensi pergi.
* Payment Delay (0.8), semakin sering pelanggan terlambat membayar, semakin tinggi risiko churn. Keterlambatan pembayaran bisa menjadi sinyal awal ketidakpuasan atau kesulitan finansial pelanggan.
* Last Interaction (0.5), semakin lama pelanggan tidak berinteraksi dengan layanan, semakin tinggi risiko churn. Pelanggan yang jarang berinteraksi cenderung sudah tidak tertarik dengan layanan.
* Age (0.4), pelanggan yang lebih tua memiliki risiko churn sedikit lebih tinggi, kemungkinan karena kebutuhan dan ekspektasi yang berbeda terhadap layanan.

**Faktor yang Menurunkan Churn (Biru):**
* Total Spend (-1.3), faktor pelindung terkuat. Semakin besar total pengeluaran pelanggan, semakin kecil risiko churn. Pelanggan yang sudah banyak berinvestasi pada layanan cenderung lebih loyal.
* Gender (-0.5), berpengaruh sedang terhadap penurunan churn, mengindikasikan ada perbedaan pola churn antara pelanggan laki-laki dan perempuan.
* Tenure (-0.1), semakin lama pelanggan berlangganan, sedikit menurunkan risiko churn. Pelanggan lama cenderung lebih loyal meski pengaruhnya kecil.
* Usage Frequency (-0.1), semakin sering pelanggan menggunakan layanan, sedikit menurunkan risiko churn, meski pengaruhnya juga kecil.
* Subscription Type (-0.05), jenis paket langganan sedikit berpengaruh dalam menurunkan churn.
* Contract Length (≈0), hampir tidak berpengaruh terhadap churn berdasarkan model ini.

#### 5.6.1 Interpretasi Bisnis per Segmen Risiko
"""

# Buat segmen risiko berdasarkan probabilitas churn
df_result['Segmen_Risiko'] = pd.cut(
    df_result['Churn_Probability'],
    bins=[0, 0.4, 0.7, 1.0],
    labels=['Rendah', 'Sedang', 'Tinggi']
)

# Pilih fitur yang relevan untuk interpretasi bisnis
fitur_bisnis = ['Support Calls', 'Payment Delay', 'Total Spend',
                'Tenure', 'Usage Frequency', 'Last Interaction']

profil_segmen = df_result.groupby('Segmen_Risiko')[fitur_bisnis].mean().round(2)

print('=== Profil Rata-rata per Segmen Risiko Churn ===')
print(profil_segmen.to_string())

"""**Insight :**
1. Pelanggan dengan risiko churn tinggi paling sering melakukan support calls, yaitu rata-rata 6,07 kali, jauh lebih tinggi dibandingkan segmen sedang (2,77) dan rendah (1,34). Hal ini menunjukkan bahwa semakin sering pelanggan menghubungi layanan pelanggan, semakin besar kemungkinan mereka melakukan churn.
2. Payment Delay juga meningkat seiring meningkatnya risiko churn, dari 9,62 hari pada segmen rendah menjadi 16,21 hari pada segmen tinggi. Artinya, pelanggan yang sering terlambat melakukan pembayaran cenderung memiliki risiko churn yang lebih tinggi.
3. Total Spend menunjukkan tren menurun. Pelanggan dengan risiko rendah memiliki rata-rata total pengeluaran 767,92, sedangkan pada risiko tinggi hanya 491,62. Ini mengindikasikan bahwa pelanggan yang berisiko tinggi cenderung memberikan nilai bisnis yang lebih rendah bagi perusahaan.
4. Tenure sedikit menurun dari 32,39 menjadi 30,37. Perbedaannya relatif kecil sehingga lama berlangganan bukan merupakan faktor pembeda utama antar segmen risiko.
5. Usage Frequency juga mengalami sedikit penurunan, dari 16,20 pada risiko rendah menjadi 15,30 pada risiko tinggi. Hal ini menunjukkan bahwa pelanggan yang berisiko churn cenderung sedikit lebih jarang menggunakan layanan.
6. Last Interaction meningkat dari 12,84 menjadi 16,11. Ini menunjukkan bahwa pelanggan dengan risiko churn tinggi memiliki jeda interaksi yang lebih lama dengan perusahaan, yang dapat menjadi indikasi menurunnya keterlibatan (engagement).

#### 5.6.2 Visualisasi Profil Pelangaan Per Segmen Risiko Churn
"""

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
axes = axes.flatten()

warna_segmen = {'Rendah': '#2ecc71', 'Sedang': '#f39c12', 'Tinggi': '#e74c3c'}

for i, fitur in enumerate(fitur_bisnis):
    nilai = profil_segmen[fitur]
    bars = axes[i].bar(
        nilai.index,
        nilai.values,
        color=[warna_segmen[s] for s in nilai.index],
        alpha=0.85, edgecolor='white', linewidth=1.5
    )
    axes[i].set_title(f'Rata-rata {fitur}', fontweight='bold')
    axes[i].set_ylabel('Nilai Rata-rata')
    for bar, val in zip(bars, nilai.values):
        axes[i].text(
            bar.get_x() + bar.get_width()/2,
            bar.get_height() + 0.1,
            f'{val:.1f}', ha='center', fontweight='bold', fontsize=10
        )

plt.suptitle('Profil Perilaku Pelanggan per Segmen Risiko Churn',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

"""Bisa dikatakan pelanggan yang memiliki resiko tinggi terhadap churn adalah pelanggan yang memiliki profil sebagai berikut :

1.   Sering menghubungi customer service
2.   Lebih sering telat melakukan pembayaran
3.   Memiliki total pengeluaran yang lebih rendah
4.   Memiliki jeda interaksi yang lebih lama

Sebaliknya, tenure dan frekuensi penggunaan hanya menunjukkan perbedaan yang relatif kecil. Oleh karena itu, faktor seperti support calls, payment delay, total spend, dan last interaction menjadi indikator utama yang dapat digunakan perusahaan untuk mengidentifikasi pelanggan yang berpotensi melakukan churn dan memberikan intervensi lebih awal.

#### 5.6.3  Jumlah pelanggan per segmen
"""

print('\n=== Jumlah Pelanggan per Segmen ===')
print(df_result['Segmen_Risiko'].value_counts().sort_index())

"""**Insight :**

Bisa terlihat berdasarkan pengelompokkan pelanggan per segmen berdasarkan kelompok "rendah terhadap churn", "sedang terhadap churn", dan "tinggi terhadap churn", segmentasi dengan kelompok "tinggi churn" masih lebih dominan atau lebih besar dari 2 kelompok sebelumnya

#### 5.6.4 Rekomendasi bisnis otomatis
"""

print('\n=== Rekomendasi Aksi Bisnis ===')
rekomendasi = {
    'Rendah'  : 'Pertahankan loyalitas → program reward & loyalty points',
    'Sedang'  : 'Cegah eskalasi → tawarkan promo atau upgrade paket',
    'Tinggi'  : 'Intervensi segera → hubungi personal, diskon retensi, prioritas support'
}
for segmen, aksi in rekomendasi.items():
    n = (df_result['Segmen_Risiko'] == segmen).sum()
    print(f'  [{segmen:6}] {n:>6,} pelanggan → {aksi}')

"""### 5.7 Pengecekan Kriteria Sukses"""

criteria = {'Recall': 0.75, 'AUC-ROC': 0.85}

print('\nPengecekan Kriteria Sukses')
print(f'{"Metrik":<12}{"Target":>8}{"Hasil":>10}{"Status":>8}')

for metrik, target in criteria.items():
    val = scores_lr[metrik]
    status = '✅' if val >= target else '❌'
    print(f'{metrik:<12}{target:>8.2f}{val:>10.4f}{status:>8}')

"""## Kesimpulan

### Berdasarkan keempat tahapan CRISP-DM di atas, dapat menjawab business question sebagai berikut:

#### 1. Berapa tingkat churn saat ini?

Berdasarkan tahap **Data Understanding**, tingkat churn saat ini adalah
**56,7%** dari total **440.832 pelanggan**, yaitu sebanyak **249.999 pelanggan**
telah melakukan churn. Angka ini menunjukkan lebih dari separuh pelanggan
berpotensi meninggalkan layanan, sehingga strategi retensi menjadi sangat krusial.

#### 2. Profil pelanggan seperti apa yang paling sering churn?

Berdasarkan tahap **Data Understanding**, pelanggan yang paling sering churn memiliki karakteristik sebagai berikut:

* Berusia lebih tua (rata-rata **41,75 tahun**)
* Masa berlangganan lebih pendek (rata-rata **30,47 bulan**)
* Lebih sering menghubungi customer support
* Lebih sering terlambat membayar
* Memiliki total pengeluaran yang lebih rendah dibanding pelanggan yang bertahan

#### 3. Faktor apa yang paling berkorelasi dengan churn?

Berdasarkan analisis korelasi pada tahap **Data Understanding** dan dikonfirmasi oleh koefisien **Logistic Regression** pada tahap **Evaluation**, tiga faktor utama yang paling berpengaruh terhadap churn adalah:

* **Support Calls** (koefisien **2,1**): semakin banyak komplain, semakin tinggi risiko churn
* **Total Spend** (koefisien **-1,3**): semakin besar pengeluaran pelanggan, semakin kecil risiko churn
* **Payment Delay** (koefisien **0,8**): semakin sering terlambat membayar, semakin tinggi risiko churn

#### 4. Apakah jenis kontrak dan paket berpengaruh terhadap churn?

Berdasarkan tahap **Data Understanding**, jenis kontrak berpengaruh signifikan. Pelanggan dengan kontrak **Monthly** memiliki tingkat churn tertinggi (100%), sedangkan kontrak **Annual** dan **Quarterly** memiliki tingkat churn yang jauh lebih rendah (sekitar 46%). Untuk jenis paket, ketiganya memiliki tingkat churn yang relatif mirip (56–58%), dengan paket **Basic** sedikit lebih tinggi. Namun berdasarkan koefisien model, **Contract Length** dan **Subscription Type** memiliki pengaruh yang relatif kecil dibandingkan faktor seperti **Support Calls**, **Total Spend**, dan **Payment Delay**.

---

### Tujuan Data Mining Tercapai

Model klasifikasi **Logistic Regression** berhasil dibangun dan mampu memprediksi status churn pelanggan berdasarkan karakteristik dan pola penggunaan, dengan hasil:

* **Recall = 0,87**, artinya model berhasil mendeteksi sekitar **87 dari 100 pelanggan** yang benar-benar akan churn, melampaui target penelitian (≥ 0,75). Naik karena melakukan thresold di step sebelumnya
* **AUC-ROC = 0,93**, menunjukkan model memiliki kemampuan yang sangat baik dalam membedakan pelanggan yang akan churn dan tidak churn, serta melampaui target penelitian (≥ 0,85).

Selain itu, melalui **threshold tuning**, threshold **0,4** dipilih karena memberikan keseimbangan terbaik antara **recall**, **precision**, dan **F1-score**, sehingga model mampu mendeteksi lebih banyak pelanggan yang berpotensi churn tanpa menurunkan performa secara signifikan.

---

### Rekomendasi Aksi Bisnis

Berdasarkan hasil segmentasi risiko churn, pelanggan dapat dikelompokkan menjadi tiga kategori sehingga perusahaan dapat menerapkan strategi retensi yang lebih tepat sasaran:

* **Segmen Risiko Rendah (38.161 pelanggan)**
  Fokus pada **mempertahankan loyalitas pelanggan** melalui program **reward**, **loyalty points**, atau penawaran eksklusif agar pelanggan tetap aktif dan loyal.

* **Segmen Risiko Sedang (11.238 pelanggan)**
  Fokus pada **mencegah peningkatan risiko churn** dengan memberikan **promo khusus**, **upgrade paket**, atau penawaran yang sesuai dengan kebutuhan pelanggan agar tetap menggunakan layanan.

* **Segmen Risiko Tinggi (38.768 pelanggan)**
  Fokus pada **intervensi segera** melalui **pendekatan personal**, pemberian **diskon retensi**, serta **prioritas layanan customer support**. Karena segmen ini memiliki karakteristik lebih sering menghubungi customer support, lebih sering terlambat membayar, memiliki total pengeluaran lebih rendah, dan jarang berinteraksi dengan perusahaan, tindakan proaktif diharapkan dapat menurunkan tingkat churn secara signifikan.

Dengan menerapkan strategi yang berbeda untuk setiap segmen risiko, perusahaan tidak hanya mampu mengidentifikasi pelanggan yang berpotensi churn, tetapi juga dapat mengalokasikan sumber daya retensi secara lebih efektif dan efisien sehingga peluang mempertahankan pelanggan menjadi lebih tinggi.
"""